"""Config loading.

Layered config: `default_config.yaml` at `_system/orchestrator/` provides the
floor; an optional product-level `config-overrides.yaml` (generated by the
product definition agent) deep-merges on top.

Schema lives in the dataclasses below; the yaml file is documentation of the
defaults, not the source of truth for shape. Adding a config field means:
1. Add it to the dataclass with a sensible default
2. Add it to default_config.yaml (so users can see + override it)
3. Read it from `_config_from_dict` if it isn't auto-handled
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml


@dataclass
class PromptVersioningConfig:
    strict: bool = False


@dataclass
class ContextBudget:
    max_input_tokens: int
    reserved_for_output: int

    @property
    def available_for_prompt(self) -> int:
        return self.max_input_tokens - self.reserved_for_output


@dataclass
class RetryConfig:
    max_attempts: int = 5
    backoff_seconds: list[int] = field(default_factory=lambda: [2, 4, 8, 16, 32])
    malformed_response_retries: int = 2


@dataclass
class ContentValidation:
    input_coverage: bool = True
    consistency: bool = False
    hallucination_flag: bool = True
    scope_compliance: bool = True


@dataclass
class ValidationConfig:
    structural: str = "always"
    content: ContentValidation = field(default_factory=ContentValidation)


@dataclass
class TelemetryConfig:
    distinct_id: str = "pm_os_user"
    backend: str = "jsonl"


@dataclass
class Config:
    prompt_versioning: PromptVersioningConfig = field(default_factory=PromptVersioningConfig)
    context_budgets: dict[str, ContextBudget] = field(default_factory=dict)
    retry: RetryConfig = field(default_factory=RetryConfig)
    validation: ValidationConfig = field(default_factory=ValidationConfig)
    telemetry: TelemetryConfig = field(default_factory=TelemetryConfig)


def default_config_path(base_dir: Path) -> Path:
    return Path(base_dir) / "_system" / "orchestrator" / "default_config.yaml"


def load_config(base_dir: Path, overrides_path: Path | None = None) -> Config:
    """Load `default_config.yaml` and optionally layer `overrides_path` on top.

    Deep merge: nested dicts merge recursively; lists and scalars are replaced.
    Missing default_config.yaml is treated as empty (all dataclass defaults apply).
    """
    base_dir = Path(base_dir)
    data = _load_yaml(default_config_path(base_dir))

    if overrides_path is not None:
        overrides = _load_yaml(Path(overrides_path))
        data = _deep_merge(data, overrides)

    return _config_from_dict(data)


def _load_yaml(path: Path) -> dict:
    if not path.exists():
        return {}
    with open(path) as f:
        return yaml.safe_load(f) or {}


def _deep_merge(base: dict, override: dict) -> dict:
    """Recursive merge — override wins on leaves; both keys preserved at nodes."""
    result = dict(base)
    for key, val in override.items():
        if key in result and isinstance(result[key], dict) and isinstance(val, dict):
            result[key] = _deep_merge(result[key], val)
        else:
            result[key] = val
    return result


def _config_from_dict(data: dict[str, Any]) -> Config:
    cfg = Config()

    if pv := data.get("prompt_versioning"):
        cfg.prompt_versioning = PromptVersioningConfig(**pv)

    if cb := data.get("context_budgets"):
        cfg.context_budgets = {model: ContextBudget(**spec) for model, spec in cb.items()}

    if r := data.get("retry"):
        cfg.retry = RetryConfig(**r)

    if v := data.get("validation"):
        content_data = v.get("content", {})
        cfg.validation = ValidationConfig(
            structural=v.get("structural", "always"),
            content=ContentValidation(**content_data),
        )

    if t := data.get("telemetry"):
        cfg.telemetry = TelemetryConfig(**t)

    return cfg
